[tool.poetry]
name = "data-cleaner"
version = "0.1.0"
description = ""
authors = ["hafsa ibrahim"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.31.1"
cryptography = "^42.0.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
